//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	config "github.com/koordinator-sh/koordinator/pkg/descheduler/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error { _ = "STUB: not implemented"; return nil }

func autoConvert_v1alpha2_ArbitrationArgs_To_config_ArbitrationArgs(in *ArbitrationArgs, out *config.ArbitrationArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_ArbitrationArgs_To_config_ArbitrationArgs is an autogenerated conversion function.
func Convert_v1alpha2_ArbitrationArgs_To_config_ArbitrationArgs(in *ArbitrationArgs, out *config.ArbitrationArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_ArbitrationArgs_To_v1alpha2_ArbitrationArgs(in *config.ArbitrationArgs, out *ArbitrationArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_ArbitrationArgs_To_v1alpha2_ArbitrationArgs is an autogenerated conversion function.
func Convert_config_ArbitrationArgs_To_v1alpha2_ArbitrationArgs(in *config.ArbitrationArgs, out *ArbitrationArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_CustomPriorityArgs_To_config_CustomPriorityArgs(in *CustomPriorityArgs, out *config.CustomPriorityArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_CustomPriorityArgs_To_v1alpha2_CustomPriorityArgs(in *config.CustomPriorityArgs, out *CustomPriorityArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_CustomPriorityArgs_To_v1alpha2_CustomPriorityArgs is an autogenerated conversion function.
func Convert_config_CustomPriorityArgs_To_v1alpha2_CustomPriorityArgs(in *config.CustomPriorityArgs, out *CustomPriorityArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_CustomPriorityPodSelector_To_config_CustomPriorityPodSelector(in *CustomPriorityPodSelector, out *config.CustomPriorityPodSelector, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_CustomPriorityPodSelector_To_config_CustomPriorityPodSelector is an autogenerated conversion function.
func Convert_v1alpha2_CustomPriorityPodSelector_To_config_CustomPriorityPodSelector(in *CustomPriorityPodSelector, out *config.CustomPriorityPodSelector, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_CustomPriorityPodSelector_To_v1alpha2_CustomPriorityPodSelector(in *config.CustomPriorityPodSelector, out *CustomPriorityPodSelector, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_CustomPriorityPodSelector_To_v1alpha2_CustomPriorityPodSelector is an autogenerated conversion function.
func Convert_config_CustomPriorityPodSelector_To_v1alpha2_CustomPriorityPodSelector(in *config.CustomPriorityPodSelector, out *CustomPriorityPodSelector, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_DeschedulerConfiguration_To_config_DeschedulerConfiguration(in *DeschedulerConfiguration, out *config.DeschedulerConfiguration, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_DeschedulerConfiguration_To_v1alpha2_DeschedulerConfiguration(in *config.DeschedulerConfiguration, out *DeschedulerConfiguration, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_DeschedulerProfile_To_config_DeschedulerProfile(in *DeschedulerProfile, out *config.DeschedulerProfile, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_DeschedulerProfile_To_config_DeschedulerProfile is an autogenerated conversion function.
func Convert_v1alpha2_DeschedulerProfile_To_config_DeschedulerProfile(in *DeschedulerProfile, out *config.DeschedulerProfile, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_DeschedulerProfile_To_v1alpha2_DeschedulerProfile(in *config.DeschedulerProfile, out *DeschedulerProfile, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_DeschedulerProfile_To_v1alpha2_DeschedulerProfile is an autogenerated conversion function.
func Convert_config_DeschedulerProfile_To_v1alpha2_DeschedulerProfile(in *config.DeschedulerProfile, out *DeschedulerProfile, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_LoadAnomalyCondition_To_config_LoadAnomalyCondition(in *LoadAnomalyCondition, out *config.LoadAnomalyCondition, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_LoadAnomalyCondition_To_config_LoadAnomalyCondition is an autogenerated conversion function.
func Convert_v1alpha2_LoadAnomalyCondition_To_config_LoadAnomalyCondition(in *LoadAnomalyCondition, out *config.LoadAnomalyCondition, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_LoadAnomalyCondition_To_v1alpha2_LoadAnomalyCondition(in *config.LoadAnomalyCondition, out *LoadAnomalyCondition, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_LoadAnomalyCondition_To_v1alpha2_LoadAnomalyCondition is an autogenerated conversion function.
func Convert_config_LoadAnomalyCondition_To_v1alpha2_LoadAnomalyCondition(in *config.LoadAnomalyCondition, out *LoadAnomalyCondition, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_LowNodeLoadArgs_To_config_LowNodeLoadArgs(in *LowNodeLoadArgs, out *config.LowNodeLoadArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_LowNodeLoadArgs_To_v1alpha2_LowNodeLoadArgs(in *config.LowNodeLoadArgs, out *LowNodeLoadArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_LowNodeLoadArgs_To_v1alpha2_LowNodeLoadArgs is an autogenerated conversion function.
func Convert_config_LowNodeLoadArgs_To_v1alpha2_LowNodeLoadArgs(in *config.LowNodeLoadArgs, out *LowNodeLoadArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_LowNodeLoadNodePool_To_config_LowNodeLoadNodePool(in *LowNodeLoadNodePool, out *config.LowNodeLoadNodePool, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_LowNodeLoadNodePool_To_config_LowNodeLoadNodePool is an autogenerated conversion function.
func Convert_v1alpha2_LowNodeLoadNodePool_To_config_LowNodeLoadNodePool(in *LowNodeLoadNodePool, out *config.LowNodeLoadNodePool, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_LowNodeLoadNodePool_To_v1alpha2_LowNodeLoadNodePool(in *config.LowNodeLoadNodePool, out *LowNodeLoadNodePool, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_LowNodeLoadNodePool_To_v1alpha2_LowNodeLoadNodePool is an autogenerated conversion function.
func Convert_config_LowNodeLoadNodePool_To_v1alpha2_LowNodeLoadNodePool(in *config.LowNodeLoadNodePool, out *LowNodeLoadNodePool, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_LowNodeLoadPodSelector_To_config_LowNodeLoadPodSelector(in *LowNodeLoadPodSelector, out *config.LowNodeLoadPodSelector, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_LowNodeLoadPodSelector_To_config_LowNodeLoadPodSelector is an autogenerated conversion function.
func Convert_v1alpha2_LowNodeLoadPodSelector_To_config_LowNodeLoadPodSelector(in *LowNodeLoadPodSelector, out *config.LowNodeLoadPodSelector, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_LowNodeLoadPodSelector_To_v1alpha2_LowNodeLoadPodSelector(in *config.LowNodeLoadPodSelector, out *LowNodeLoadPodSelector, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_LowNodeLoadPodSelector_To_v1alpha2_LowNodeLoadPodSelector is an autogenerated conversion function.
func Convert_config_LowNodeLoadPodSelector_To_v1alpha2_LowNodeLoadPodSelector(in *config.LowNodeLoadPodSelector, out *LowNodeLoadPodSelector, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_MigrationControllerArgs_To_config_MigrationControllerArgs(in *MigrationControllerArgs, out *config.MigrationControllerArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_MigrationControllerArgs_To_config_MigrationControllerArgs is an autogenerated conversion function.
func Convert_v1alpha2_MigrationControllerArgs_To_config_MigrationControllerArgs(in *MigrationControllerArgs, out *config.MigrationControllerArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_MigrationControllerArgs_To_v1alpha2_MigrationControllerArgs(in *config.MigrationControllerArgs, out *MigrationControllerArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_MigrationControllerArgs_To_v1alpha2_MigrationControllerArgs is an autogenerated conversion function.
func Convert_config_MigrationControllerArgs_To_v1alpha2_MigrationControllerArgs(in *config.MigrationControllerArgs, out *MigrationControllerArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_MigrationObjectLimiter_To_config_MigrationObjectLimiter(in *MigrationObjectLimiter, out *config.MigrationObjectLimiter, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_MigrationObjectLimiter_To_config_MigrationObjectLimiter is an autogenerated conversion function.
func Convert_v1alpha2_MigrationObjectLimiter_To_config_MigrationObjectLimiter(in *MigrationObjectLimiter, out *config.MigrationObjectLimiter, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_MigrationObjectLimiter_To_v1alpha2_MigrationObjectLimiter(in *config.MigrationObjectLimiter, out *MigrationObjectLimiter, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_MigrationObjectLimiter_To_v1alpha2_MigrationObjectLimiter is an autogenerated conversion function.
func Convert_config_MigrationObjectLimiter_To_v1alpha2_MigrationObjectLimiter(in *config.MigrationObjectLimiter, out *MigrationObjectLimiter, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_Namespaces_To_config_Namespaces(in *Namespaces, out *config.Namespaces, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_Namespaces_To_config_Namespaces is an autogenerated conversion function.
func Convert_v1alpha2_Namespaces_To_config_Namespaces(in *Namespaces, out *config.Namespaces, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_Namespaces_To_v1alpha2_Namespaces(in *config.Namespaces, out *Namespaces, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_Namespaces_To_v1alpha2_Namespaces is an autogenerated conversion function.
func Convert_config_Namespaces_To_v1alpha2_Namespaces(in *config.Namespaces, out *Namespaces, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_Plugin_To_config_Plugin(in *Plugin, out *config.Plugin, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_Plugin_To_config_Plugin is an autogenerated conversion function.
func Convert_v1alpha2_Plugin_To_config_Plugin(in *Plugin, out *config.Plugin, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_Plugin_To_v1alpha2_Plugin(in *config.Plugin, out *Plugin, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_Plugin_To_v1alpha2_Plugin is an autogenerated conversion function.
func Convert_config_Plugin_To_v1alpha2_Plugin(in *config.Plugin, out *Plugin, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_PluginConfig_To_config_PluginConfig(in *PluginConfig, out *config.PluginConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_PluginConfig_To_config_PluginConfig is an autogenerated conversion function.
func Convert_v1alpha2_PluginConfig_To_config_PluginConfig(in *PluginConfig, out *config.PluginConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_PluginConfig_To_v1alpha2_PluginConfig(in *config.PluginConfig, out *PluginConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_PluginConfig_To_v1alpha2_PluginConfig is an autogenerated conversion function.
func Convert_config_PluginConfig_To_v1alpha2_PluginConfig(in *config.PluginConfig, out *PluginConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_PluginSet_To_config_PluginSet(in *PluginSet, out *config.PluginSet, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_PluginSet_To_config_PluginSet is an autogenerated conversion function.
func Convert_v1alpha2_PluginSet_To_config_PluginSet(in *PluginSet, out *config.PluginSet, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_PluginSet_To_v1alpha2_PluginSet(in *config.PluginSet, out *PluginSet, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_PluginSet_To_v1alpha2_PluginSet is an autogenerated conversion function.
func Convert_config_PluginSet_To_v1alpha2_PluginSet(in *config.PluginSet, out *PluginSet, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_Plugins_To_config_Plugins(in *Plugins, out *config.Plugins, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_Plugins_To_config_Plugins is an autogenerated conversion function.
func Convert_v1alpha2_Plugins_To_config_Plugins(in *Plugins, out *config.Plugins, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_Plugins_To_v1alpha2_Plugins(in *config.Plugins, out *Plugins, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_Plugins_To_v1alpha2_Plugins is an autogenerated conversion function.
func Convert_config_Plugins_To_v1alpha2_Plugins(in *config.Plugins, out *Plugins, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_PriorityThreshold_To_config_PriorityThreshold(in *PriorityThreshold, out *config.PriorityThreshold, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_PriorityThreshold_To_config_PriorityThreshold is an autogenerated conversion function.
func Convert_v1alpha2_PriorityThreshold_To_config_PriorityThreshold(in *PriorityThreshold, out *config.PriorityThreshold, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_PriorityThreshold_To_v1alpha2_PriorityThreshold(in *config.PriorityThreshold, out *PriorityThreshold, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_PriorityThreshold_To_v1alpha2_PriorityThreshold is an autogenerated conversion function.
func Convert_config_PriorityThreshold_To_v1alpha2_PriorityThreshold(in *config.PriorityThreshold, out *PriorityThreshold, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1alpha2_ResourcePriority_To_config_ResourcePriority(in *ResourcePriority, out *config.ResourcePriority, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1alpha2_ResourcePriority_To_config_ResourcePriority is an autogenerated conversion function.
func Convert_v1alpha2_ResourcePriority_To_config_ResourcePriority(in *ResourcePriority, out *config.ResourcePriority, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_ResourcePriority_To_v1alpha2_ResourcePriority(in *config.ResourcePriority, out *ResourcePriority, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_ResourcePriority_To_v1alpha2_ResourcePriority is an autogenerated conversion function.
func Convert_config_ResourcePriority_To_v1alpha2_ResourcePriority(in *config.ResourcePriority, out *ResourcePriority, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}
