//go:build !ignore_autogenerated

/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package configuration

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUBurstCfg) DeepCopyInto(out *CPUBurstCfg) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUBurstCfg.
func (in *CPUBurstCfg) DeepCopy() *CPUBurstCfg { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUNormalizationCfg) DeepCopyInto(out *CPUNormalizationCfg) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUNormalizationCfg.
func (in *CPUNormalizationCfg) DeepCopy() *CPUNormalizationCfg {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUNormalizationStrategy) DeepCopyInto(out *CPUNormalizationStrategy) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUNormalizationStrategy.
func (in *CPUNormalizationStrategy) DeepCopy() *CPUNormalizationStrategy {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColocationCfg) DeepCopyInto(out *ColocationCfg) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColocationCfg.
func (in *ColocationCfg) DeepCopy() *ColocationCfg { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColocationStrategy) DeepCopyInto(out *ColocationStrategy) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColocationStrategy.
func (in *ColocationStrategy) DeepCopy() *ColocationStrategy { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColocationStrategyExtender) DeepCopyInto(out *ColocationStrategyExtender) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColocationStrategyExtender.
func (in *ColocationStrategyExtender) DeepCopy() *ColocationStrategyExtender {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionCfgMap) DeepCopyInto(out *ExtensionCfgMap) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionCfgMap.
func (in *ExtensionCfgMap) DeepCopy() *ExtensionCfgMap { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostApplicationCfg) DeepCopyInto(out *HostApplicationCfg) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostApplicationCfg.
func (in *HostApplicationCfg) DeepCopy() *HostApplicationCfg { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRatioCfg) DeepCopyInto(out *ModelRatioCfg) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRatioCfg.
func (in *ModelRatioCfg) DeepCopy() *ModelRatioCfg { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCPUBurstCfg) DeepCopyInto(out *NodeCPUBurstCfg) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCPUBurstCfg.
func (in *NodeCPUBurstCfg) DeepCopy() *NodeCPUBurstCfg { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCPUNormalizationCfg) DeepCopyInto(out *NodeCPUNormalizationCfg) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCPUNormalizationCfg.
func (in *NodeCPUNormalizationCfg) DeepCopy() *NodeCPUNormalizationCfg {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCfgProfile) DeepCopyInto(out *NodeCfgProfile) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCfgProfile.
func (in *NodeCfgProfile) DeepCopy() *NodeCfgProfile { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeColocationCfg) DeepCopyInto(out *NodeColocationCfg) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeColocationCfg.
func (in *NodeColocationCfg) DeepCopy() *NodeColocationCfg { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHostApplicationCfg) DeepCopyInto(out *NodeHostApplicationCfg) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHostApplicationCfg.
func (in *NodeHostApplicationCfg) DeepCopy() *NodeHostApplicationCfg {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceAmplificationCfg) DeepCopyInto(out *NodeResourceAmplificationCfg) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceAmplificationCfg.
func (in *NodeResourceAmplificationCfg) DeepCopy() *NodeResourceAmplificationCfg {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceQOSStrategy) DeepCopyInto(out *NodeResourceQOSStrategy) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceQOSStrategy.
func (in *NodeResourceQOSStrategy) DeepCopy() *NodeResourceQOSStrategy {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceThresholdStrategy) DeepCopyInto(out *NodeResourceThresholdStrategy) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceThresholdStrategy.
func (in *NodeResourceThresholdStrategy) DeepCopy() *NodeResourceThresholdStrategy {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemStrategy) DeepCopyInto(out *NodeSystemStrategy) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemStrategy.
func (in *NodeSystemStrategy) DeepCopy() *NodeSystemStrategy { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAmplificationCfg) DeepCopyInto(out *ResourceAmplificationCfg) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAmplificationCfg.
func (in *ResourceAmplificationCfg) DeepCopy() *ResourceAmplificationCfg {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAmplificationStrategy) DeepCopyInto(out *ResourceAmplificationStrategy) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAmplificationStrategy.
func (in *ResourceAmplificationStrategy) DeepCopy() *ResourceAmplificationStrategy {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQOSCfg) DeepCopyInto(out *ResourceQOSCfg) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQOSCfg.
func (in *ResourceQOSCfg) DeepCopy() *ResourceQOSCfg { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceThresholdCfg) DeepCopyInto(out *ResourceThresholdCfg) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceThresholdCfg.
func (in *ResourceThresholdCfg) DeepCopy() *ResourceThresholdCfg {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemCfg) DeepCopyInto(out *SystemCfg) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemCfg.
func (in *SystemCfg) DeepCopy() *SystemCfg { _ = "STUB: not implemented"; return nil }
