// /*
// Copyright 2022 The Koordinator Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/koordlet/runtimehooks/nri/types.go
//
// Generated by this command:
//
//	mockgen -source pkg/koordlet/runtimehooks/nri/types.go -destination pkg/koordlet/runtimehooks/nri/mock_nri.go -copyright_file ./hack/boilerplate/boilerplate.go.txt -package nri
//

// Package nri is a generated GoMock package.
package nri

import (
	context "context"
	time "time"

	api "github.com/containerd/nri/pkg/api"
	log "github.com/containerd/nri/pkg/log"
	gomock "go.uber.org/mock/gomock"
)

// MockStubInterface is a mock of StubInterface interface.
type MockStubInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStubInterfaceMockRecorder
	isgomock struct{}
}

// MockStubInterfaceMockRecorder is the mock recorder for MockStubInterface.
type MockStubInterfaceMockRecorder struct {
	mock *MockStubInterface
}

// NewMockStubInterface creates a new mock instance.
func NewMockStubInterface(ctrl *gomock.Controller) *MockStubInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStubInterface) EXPECT() *MockStubInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// Logger mocks base method.
	return nil
}

func (m *MockStubInterface) Logger() log.Logger { _ = "STUB: not implemented"; return *new(log.Logger) }

// Logger indicates an expected call of Logger.
func (mr *MockStubInterfaceMockRecorder) Logger() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegistrationTimeout mocks base method.
func (m *MockStubInterface) RegistrationTimeout() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

// RegistrationTimeout indicates an expected call of RegistrationTimeout.
func (mr *MockStubInterfaceMockRecorder) RegistrationTimeout() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RequestTimeout mocks base method.
func (m *MockStubInterface) RequestTimeout() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

// RequestTimeout indicates an expected call of RequestTimeout.
func (mr *MockStubInterfaceMockRecorder) RequestTimeout() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockStubInterface) Run(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Run indicates an expected call of Run.
func (mr *MockStubInterfaceMockRecorder) Run(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockStubInterface) Start(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Start indicates an expected call of Start.
func (mr *MockStubInterfaceMockRecorder) Start(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockStubInterface) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockStubInterfaceMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }

// UpdateContainers mocks base method.
func (m *MockStubInterface) UpdateContainers(arg0 []*api.ContainerUpdate) ([]*api.ContainerUpdate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateContainers indicates an expected call of UpdateContainers.
func (mr *MockStubInterfaceMockRecorder) UpdateContainers(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Wait mocks base method.
func (m *MockStubInterface) Wait() { _ = "STUB: not implemented"; return }

// Wait indicates an expected call of Wait.
func (mr *MockStubInterfaceMockRecorder) Wait() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	_ = "STUB: not implemented"

	// Configure mocks base method.
	return nil
}

func (m *MockServer) Configure(ctx context.Context, config, runtime, version string) (api.EventMask, error) {
	_ = "STUB: not implemented"
	return *new(api.EventMask), nil
}

// Configure indicates an expected call of Configure.
func (mr *MockServerMockRecorder) Configure(ctx, config, runtime, version any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateContainer mocks base method.
func (m *MockServer) CreateContainer(arg0 context.Context, arg1 *api.PodSandbox, arg2 *api.Container) (*api.ContainerAdjustment, []*api.ContainerUpdate, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockServerMockRecorder) CreateContainer(arg0, arg1, arg2 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemovePodSandbox mocks base method.
func (m *MockServer) RemovePodSandbox(arg0 context.Context, arg1 *api.PodSandbox) error {
	_ = "STUB: not implemented"
	return nil
}

// RemovePodSandbox indicates an expected call of RemovePodSandbox.
func (mr *MockServerMockRecorder) RemovePodSandbox(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RunPodSandbox mocks base method.
func (m *MockServer) RunPodSandbox(arg0 context.Context, arg1 *api.PodSandbox) error {
	_ = "STUB: not implemented"
	return nil
}

// RunPodSandbox indicates an expected call of RunPodSandbox.
func (mr *MockServerMockRecorder) RunPodSandbox(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockServer) Start() error { _ = "STUB: not implemented"; return nil }

// Start indicates an expected call of Start.
func (mr *MockServerMockRecorder) Start() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Synchronize mocks base method.
func (m *MockServer) Synchronize(arg0 context.Context, arg1 []*api.PodSandbox, arg2 []*api.Container) ([]*api.ContainerUpdate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Synchronize indicates an expected call of Synchronize.
func (mr *MockServerMockRecorder) Synchronize(arg0, arg1, arg2 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateContainer mocks base method.
func (m *MockServer) UpdateContainer(arg0 context.Context, arg1 *api.PodSandbox, arg2 *api.Container, arg3 *api.LinuxResources) ([]*api.ContainerUpdate, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateContainer indicates an expected call of UpdateContainer.
func (mr *MockServerMockRecorder) UpdateContainer(arg0, arg1, arg2, arg3 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
