/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned"
	analysisv1alpha1 "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/typed/analysis/v1alpha1"
	configv1alpha1 "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/typed/config/v1alpha1"
	quotav1alpha1 "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/typed/quota/v1alpha1"
	schedulingv1alpha1 "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/typed/scheduling/v1alpha1"
	slov1alpha1 "github.com/koordinator-sh/koordinator/pkg/client/clientset/versioned/typed/slo/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any field management, validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
//
// Deprecated: NewClientset replaces this with support for field management, which significantly improves
// server side apply testing. NewClientset is only available when apply configurations are generated (e.g.
// via --with-applyconfig).
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	_ = "STUB: not implemented"
	return nil
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	_ = "STUB: not implemented"
	return *new(discovery.DiscoveryInterface)
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	_ = "STUB: not implemented"

	// IsWatchListSemanticsSupported informs the reflector that this client
	// doesn't support WatchList semantics.
	//
	// This is a synthetic method whose sole purpose is to satisfy the optional
	// interface check performed by the reflector.
	// Returning true signals that WatchList can NOT be used.
	// No additional logic is implemented here.
	return *new(testing.ObjectTracker)
}

func (c *Clientset) IsWatchListSemanticsUnSupported() bool { _ = "STUB: not implemented"; return false }

var (
	_ clientset.Interface = &Clientset{}
	_ testing.FakeClient  = &Clientset{}
)

// AnalysisV1alpha1 retrieves the AnalysisV1alpha1Client
func (c *Clientset) AnalysisV1alpha1() analysisv1alpha1.AnalysisV1alpha1Interface {
	_ = "STUB: not implemented"
	return *new(analysisv1alpha1.AnalysisV1alpha1Interface)
}

// ConfigV1alpha1 retrieves the ConfigV1alpha1Client
func (c *Clientset) ConfigV1alpha1() configv1alpha1.ConfigV1alpha1Interface {
	_ = "STUB: not implemented"
	return *new(configv1alpha1.ConfigV1alpha1Interface)
}

// QuotaV1alpha1 retrieves the QuotaV1alpha1Client
func (c *Clientset) QuotaV1alpha1() quotav1alpha1.QuotaV1alpha1Interface {
	_ = "STUB: not implemented"
	return *new(quotav1alpha1.QuotaV1alpha1Interface)
}

// SchedulingV1alpha1 retrieves the SchedulingV1alpha1Client
func (c *Clientset) SchedulingV1alpha1() schedulingv1alpha1.SchedulingV1alpha1Interface {
	_ = "STUB: not implemented"
	return *new(schedulingv1alpha1.SchedulingV1alpha1Interface)
}

// SloV1alpha1 retrieves the SloV1alpha1Client
func (c *Clientset) SloV1alpha1() slov1alpha1.SloV1alpha1Interface {
	_ = "STUB: not implemented"
	return *new(slov1alpha1.SloV1alpha1Interface)
}
