// /*
// Copyright 2022 The Koordinator Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/koordlet/metriccache/tsdb_storage.go
//
// Generated by this command:
//
//	mockgen -source pkg/koordlet/metriccache/tsdb_storage.go -destination pkg/koordlet/metriccache/mockmetriccache/mock_tsdb_storage.go -copyright_file ./hack/boilerplate/boilerplate.go.txt
//

// Package mock_metriccache is a generated GoMock package.
package mock_metriccache

import (
	time "time"

	metriccache "github.com/koordinator-sh/koordinator/pkg/koordlet/metriccache"
	gomock "go.uber.org/mock/gomock"
)

// MockTSDBStorage is a mock of TSDBStorage interface.
type MockTSDBStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTSDBStorageMockRecorder
	isgomock struct{}
}

// MockTSDBStorageMockRecorder is the mock recorder for MockTSDBStorage.
type MockTSDBStorageMockRecorder struct {
	mock *MockTSDBStorage
}

// NewMockTSDBStorage creates a new mock instance.
func NewMockTSDBStorage(ctrl *gomock.Controller) *MockTSDBStorage {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTSDBStorage) EXPECT() *MockTSDBStorageMockRecorder {
	_ = "STUB: not implemented"

	// Appender mocks base method.
	return nil
}

func (m *MockTSDBStorage) Appender() metriccache.Appender {
	_ = "STUB: not implemented"
	return *new(metriccache.Appender)
}

// Appender indicates an expected call of Appender.
func (mr *MockTSDBStorageMockRecorder) Appender() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Close mocks base method.
func (m *MockTSDBStorage) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockTSDBStorageMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Querier mocks base method.
func (m *MockTSDBStorage) Querier(startTime, endTime time.Time) (metriccache.Querier, error) {
	_ = "STUB: not implemented"
	return *new(metriccache.Querier), nil
}

// Querier indicates an expected call of Querier.
func (mr *MockTSDBStorageMockRecorder) Querier(startTime, endTime any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAppendable is a mock of Appendable interface.
type MockAppendable struct {
	ctrl     *gomock.Controller
	recorder *MockAppendableMockRecorder
	isgomock struct{}
}

// MockAppendableMockRecorder is the mock recorder for MockAppendable.
type MockAppendableMockRecorder struct {
	mock *MockAppendable
}

// NewMockAppendable creates a new mock instance.
func NewMockAppendable(ctrl *gomock.Controller) *MockAppendable {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppendable) EXPECT() *MockAppendableMockRecorder {
	_ = "STUB: not implemented"

	// Appender mocks base method.
	return nil
}

func (m *MockAppendable) Appender() metriccache.Appender {
	_ = "STUB: not implemented"
	return *new(metriccache.Appender)
}

// Appender indicates an expected call of Appender.
func (mr *MockAppendableMockRecorder) Appender() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAppender is a mock of Appender interface.
type MockAppender struct {
	ctrl     *gomock.Controller
	recorder *MockAppenderMockRecorder
	isgomock struct{}
}

// MockAppenderMockRecorder is the mock recorder for MockAppender.
type MockAppenderMockRecorder struct {
	mock *MockAppender
}

// NewMockAppender creates a new mock instance.
func NewMockAppender(ctrl *gomock.Controller) *MockAppender { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppender) EXPECT() *MockAppenderMockRecorder {
	_ = "STUB: not implemented"

	// Append mocks base method.
	return nil
}

func (m *MockAppender) Append(s []metriccache.MetricSample) error {
	_ = "STUB: not implemented"
	return nil
}

// Append indicates an expected call of Append.
func (mr *MockAppenderMockRecorder) Append(s any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Commit mocks base method.
func (m *MockAppender) Commit() error { _ = "STUB: not implemented"; return nil }

// Commit indicates an expected call of Commit.
func (mr *MockAppenderMockRecorder) Commit() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockQueryable is a mock of Queryable interface.
type MockQueryable struct {
	ctrl     *gomock.Controller
	recorder *MockQueryableMockRecorder
	isgomock struct{}
}

// MockQueryableMockRecorder is the mock recorder for MockQueryable.
type MockQueryableMockRecorder struct {
	mock *MockQueryable
}

// NewMockQueryable creates a new mock instance.
func NewMockQueryable(ctrl *gomock.Controller) *MockQueryable {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryable) EXPECT() *MockQueryableMockRecorder {
	_ = "STUB: not implemented"

	// Querier mocks base method.
	return nil
}

func (m *MockQueryable) Querier(startTime, endTime time.Time) (metriccache.Querier, error) {
	_ = "STUB: not implemented"
	return *new(metriccache.Querier), nil
}

// Querier indicates an expected call of Querier.
func (mr *MockQueryableMockRecorder) Querier(startTime, endTime any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockQuerier) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockQuerierMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Query mocks base method.
func (m *MockQuerier) Query(meta metriccache.MetricMeta, hints *metriccache.QueryHints, result metriccache.MetricResult) error {
	_ = "STUB: not implemented"
	return nil
}

// Query indicates an expected call of Query.
func (mr *MockQuerierMockRecorder) Query(meta, hints, result any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueryAndClose mocks base method.
func (m *MockQuerier) QueryAndClose(meta metriccache.MetricMeta, hints *metriccache.QueryHints, result metriccache.MetricResult) error {
	_ = "STUB: not implemented"
	return nil
}

// QueryAndClose indicates an expected call of QueryAndClose.
func (mr *MockQuerierMockRecorder) QueryAndClose(meta, hints, result any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
