// /*
// Copyright 2022 The Koordinator Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/koordlet/metriccache/metric_cache.go
//
// Generated by this command:
//
//	mockgen -source pkg/koordlet/metriccache/metric_cache.go -destination pkg/koordlet/metriccache/mockmetriccache/mock.go -aux_files github.com/koordinator-sh/koordinator/pkg/koordlet/metriccache=pkg/koordlet/metriccache/tsdb_storage.go,github.com/koordinator-sh/koordinator/pkg/koordlet/metriccache=pkg/koordlet/metriccache/kv_storage.go -copyright_file ./hack/boilerplate/boilerplate.go.txt
//

// Package mock_metriccache is a generated GoMock package.
package mock_metriccache

import (
	time "time"

	metriccache "github.com/koordinator-sh/koordinator/pkg/koordlet/metriccache"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricCache is a mock of MetricCache interface.
type MockMetricCache struct {
	ctrl     *gomock.Controller
	recorder *MockMetricCacheMockRecorder
	isgomock struct{}
}

// MockMetricCacheMockRecorder is the mock recorder for MockMetricCache.
type MockMetricCacheMockRecorder struct {
	mock *MockMetricCache
}

// NewMockMetricCache creates a new mock instance.
func NewMockMetricCache(ctrl *gomock.Controller) *MockMetricCache {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricCache) EXPECT() *MockMetricCacheMockRecorder {
	_ = "STUB: not implemented"

	// Appender mocks base method.
	return nil
}

func (m *MockMetricCache) Appender() metriccache.Appender {
	_ = "STUB: not implemented"
	return *new(metriccache.Appender)
}

// Appender indicates an expected call of Appender.
func (mr *MockMetricCacheMockRecorder) Appender() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Close mocks base method.
func (m *MockMetricCache) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockMetricCacheMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Get mocks base method.
func (m *MockMetricCache) Get(key any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// Get indicates an expected call of Get.
func (mr *MockMetricCacheMockRecorder) Get(key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Querier mocks base method.
func (m *MockMetricCache) Querier(startTime, endTime time.Time) (metriccache.Querier, error) {
	_ = "STUB: not implemented"
	return *new(metriccache.Querier), nil
}

// Querier indicates an expected call of Querier.
func (mr *MockMetricCacheMockRecorder) Querier(startTime, endTime any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockMetricCache) Run(stopCh <-chan struct{}) error { _ = "STUB: not implemented"; return nil }

// Run indicates an expected call of Run.
func (mr *MockMetricCacheMockRecorder) Run(stopCh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Set mocks base method.
func (m *MockMetricCache) Set(key, value any) { _ = "STUB: not implemented"; return }

// Set indicates an expected call of Set.
func (mr *MockMetricCacheMockRecorder) Set(key, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
