// /*
// Copyright 2022 The Koordinator Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/koordlet/statesinformer/api.go
//
// Generated by this command:
//
//	mockgen -source pkg/koordlet/statesinformer/api.go -destination pkg/koordlet/statesinformer/mockstatesinformer/mock.go -aux_files github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer=pkg/koordlet/statesinformer/api.go -copyright_file ./hack/boilerplate/boilerplate.go.txt
//

// Package mock_statesinformer is a generated GoMock package.
package mock_statesinformer

import (
	v1alpha1 "github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha1"
	v1alpha10 "github.com/koordinator-sh/koordinator/apis/slo/v1alpha1"
	statesinformer "github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockStatesInformer is a mock of StatesInformer interface.
type MockStatesInformer struct {
	ctrl     *gomock.Controller
	recorder *MockStatesInformerMockRecorder
	isgomock struct{}
}

// MockStatesInformerMockRecorder is the mock recorder for MockStatesInformer.
type MockStatesInformerMockRecorder struct {
	mock *MockStatesInformer
}

// NewMockStatesInformer creates a new mock instance.
func NewMockStatesInformer(ctrl *gomock.Controller) *MockStatesInformer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatesInformer) EXPECT() *MockStatesInformerMockRecorder {
	_ = "STUB: not implemented"

	// GetAllPods mocks base method.
	return nil
}

func (m *MockStatesInformer) GetAllPods() []*statesinformer.PodMeta {
	_ = "STUB: not implemented"
	return nil
}

// GetAllPods indicates an expected call of GetAllPods.
func (mr *MockStatesInformerMockRecorder) GetAllPods() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNode mocks base method.
func (m *MockStatesInformer) GetNode() *v1.Node { _ = "STUB: not implemented"; return nil }

// GetNode indicates an expected call of GetNode.
func (mr *MockStatesInformerMockRecorder) GetNode() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeMetricSpec mocks base method.
func (m *MockStatesInformer) GetNodeMetricSpec() *v1alpha10.NodeMetricSpec {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeMetricSpec indicates an expected call of GetNodeMetricSpec.
func (mr *MockStatesInformerMockRecorder) GetNodeMetricSpec() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeSLO mocks base method.
func (m *MockStatesInformer) GetNodeSLO() *v1alpha10.NodeSLO { _ = "STUB: not implemented"; return nil }

// GetNodeSLO indicates an expected call of GetNodeSLO.
func (mr *MockStatesInformerMockRecorder) GetNodeSLO() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeTopo mocks base method.
func (m *MockStatesInformer) GetNodeTopo() *v1alpha1.NodeResourceTopology {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeTopo indicates an expected call of GetNodeTopo.
func (mr *MockStatesInformerMockRecorder) GetNodeTopo() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetVolumeName mocks base method.
func (m *MockStatesInformer) GetVolumeName(pvcNamespace, pvcName string) string {
	_ = "STUB: not implemented"
	return ""
}

// GetVolumeName indicates an expected call of GetVolumeName.
func (mr *MockStatesInformerMockRecorder) GetVolumeName(pvcNamespace, pvcName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HasSynced mocks base method.
func (m *MockStatesInformer) HasSynced() bool { _ = "STUB: not implemented"; return false }

// HasSynced indicates an expected call of HasSynced.
func (mr *MockStatesInformerMockRecorder) HasSynced() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterCallbacks mocks base method.
func (m *MockStatesInformer) RegisterCallbacks(objType statesinformer.RegisterType, name, description string, callbackFn statesinformer.UpdateCbFn) {
	_ = "STUB: not implemented"
	return
}

// RegisterCallbacks indicates an expected call of RegisterCallbacks.
func (mr *MockStatesInformerMockRecorder) RegisterCallbacks(objType, name, description, callbackFn any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockStatesInformer) Run(stopCh <-chan struct{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Run indicates an expected call of Run.
func (mr *MockStatesInformerMockRecorder) Run(stopCh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
