//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	config "github.com/koordinator-sh/koordinator/pkg/scheduler/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error { _ = "STUB: not implemented"; return nil }

func autoConvert_v1_CoschedulingArgs_To_config_CoschedulingArgs(in *CoschedulingArgs, out *config.CoschedulingArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_CoschedulingArgs_To_config_CoschedulingArgs is an autogenerated conversion function.
func Convert_v1_CoschedulingArgs_To_config_CoschedulingArgs(in *CoschedulingArgs, out *config.CoschedulingArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_CoschedulingArgs_To_v1_CoschedulingArgs(in *config.CoschedulingArgs, out *CoschedulingArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_CoschedulingArgs_To_v1_CoschedulingArgs is an autogenerated conversion function.
func Convert_config_CoschedulingArgs_To_v1_CoschedulingArgs(in *config.CoschedulingArgs, out *CoschedulingArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_DeviceShareArgs_To_config_DeviceShareArgs(in *DeviceShareArgs, out *config.DeviceShareArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_DeviceShareArgs_To_config_DeviceShareArgs is an autogenerated conversion function.
func Convert_v1_DeviceShareArgs_To_config_DeviceShareArgs(in *DeviceShareArgs, out *config.DeviceShareArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_DeviceShareArgs_To_v1_DeviceShareArgs(in *config.DeviceShareArgs, out *DeviceShareArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_DeviceShareArgs_To_v1_DeviceShareArgs is an autogenerated conversion function.
func Convert_config_DeviceShareArgs_To_v1_DeviceShareArgs(in *config.DeviceShareArgs, out *DeviceShareArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_ElasticQuotaArgs_To_config_ElasticQuotaArgs(in *ElasticQuotaArgs, out *config.ElasticQuotaArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_ElasticQuotaArgs_To_config_ElasticQuotaArgs is an autogenerated conversion function.
func Convert_v1_ElasticQuotaArgs_To_config_ElasticQuotaArgs(in *ElasticQuotaArgs, out *config.ElasticQuotaArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_ElasticQuotaArgs_To_v1_ElasticQuotaArgs(in *config.ElasticQuotaArgs, out *ElasticQuotaArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_ElasticQuotaArgs_To_v1_ElasticQuotaArgs is an autogenerated conversion function.
func Convert_config_ElasticQuotaArgs_To_v1_ElasticQuotaArgs(in *config.ElasticQuotaArgs, out *ElasticQuotaArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_GPUShareUnsupportedModel_To_config_GPUShareUnsupportedModel(in *GPUShareUnsupportedModel, out *config.GPUShareUnsupportedModel, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_GPUShareUnsupportedModel_To_config_GPUShareUnsupportedModel is an autogenerated conversion function.
func Convert_v1_GPUShareUnsupportedModel_To_config_GPUShareUnsupportedModel(in *GPUShareUnsupportedModel, out *config.GPUShareUnsupportedModel, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_GPUShareUnsupportedModel_To_v1_GPUShareUnsupportedModel(in *config.GPUShareUnsupportedModel, out *GPUShareUnsupportedModel, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_GPUShareUnsupportedModel_To_v1_GPUShareUnsupportedModel is an autogenerated conversion function.
func Convert_config_GPUShareUnsupportedModel_To_v1_GPUShareUnsupportedModel(in *config.GPUShareUnsupportedModel, out *GPUShareUnsupportedModel, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_GPUSharedResourceTemplatesConfig_To_config_GPUSharedResourceTemplatesConfig(in *GPUSharedResourceTemplatesConfig, out *config.GPUSharedResourceTemplatesConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_GPUSharedResourceTemplatesConfig_To_config_GPUSharedResourceTemplatesConfig is an autogenerated conversion function.
func Convert_v1_GPUSharedResourceTemplatesConfig_To_config_GPUSharedResourceTemplatesConfig(in *GPUSharedResourceTemplatesConfig, out *config.GPUSharedResourceTemplatesConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_GPUSharedResourceTemplatesConfig_To_v1_GPUSharedResourceTemplatesConfig(in *config.GPUSharedResourceTemplatesConfig, out *GPUSharedResourceTemplatesConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_GPUSharedResourceTemplatesConfig_To_v1_GPUSharedResourceTemplatesConfig is an autogenerated conversion function.
func Convert_config_GPUSharedResourceTemplatesConfig_To_v1_GPUSharedResourceTemplatesConfig(in *config.GPUSharedResourceTemplatesConfig, out *GPUSharedResourceTemplatesConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_HookPluginConf_To_config_HookPluginConf(in *HookPluginConf, out *config.HookPluginConf, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_HookPluginConf_To_config_HookPluginConf is an autogenerated conversion function.
func Convert_v1_HookPluginConf_To_config_HookPluginConf(in *HookPluginConf, out *config.HookPluginConf, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_HookPluginConf_To_v1_HookPluginConf(in *config.HookPluginConf, out *HookPluginConf, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_HookPluginConf_To_v1_HookPluginConf is an autogenerated conversion function.
func Convert_config_HookPluginConf_To_v1_HookPluginConf(in *config.HookPluginConf, out *HookPluginConf, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_LoadAwareSchedulingAggregatedArgs_To_config_LoadAwareSchedulingAggregatedArgs(in *LoadAwareSchedulingAggregatedArgs, out *config.LoadAwareSchedulingAggregatedArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_LoadAwareSchedulingAggregatedArgs_To_config_LoadAwareSchedulingAggregatedArgs is an autogenerated conversion function.
func Convert_v1_LoadAwareSchedulingAggregatedArgs_To_config_LoadAwareSchedulingAggregatedArgs(in *LoadAwareSchedulingAggregatedArgs, out *config.LoadAwareSchedulingAggregatedArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_LoadAwareSchedulingAggregatedArgs_To_v1_LoadAwareSchedulingAggregatedArgs(in *config.LoadAwareSchedulingAggregatedArgs, out *LoadAwareSchedulingAggregatedArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_LoadAwareSchedulingAggregatedArgs_To_v1_LoadAwareSchedulingAggregatedArgs is an autogenerated conversion function.
func Convert_config_LoadAwareSchedulingAggregatedArgs_To_v1_LoadAwareSchedulingAggregatedArgs(in *config.LoadAwareSchedulingAggregatedArgs, out *LoadAwareSchedulingAggregatedArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_LoadAwareSchedulingArgs_To_config_LoadAwareSchedulingArgs(in *LoadAwareSchedulingArgs, out *config.LoadAwareSchedulingArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_LoadAwareSchedulingArgs_To_config_LoadAwareSchedulingArgs is an autogenerated conversion function.
func Convert_v1_LoadAwareSchedulingArgs_To_config_LoadAwareSchedulingArgs(in *LoadAwareSchedulingArgs, out *config.LoadAwareSchedulingArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_LoadAwareSchedulingArgs_To_v1_LoadAwareSchedulingArgs(in *config.LoadAwareSchedulingArgs, out *LoadAwareSchedulingArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_LoadAwareSchedulingArgs_To_v1_LoadAwareSchedulingArgs is an autogenerated conversion function.
func Convert_config_LoadAwareSchedulingArgs_To_v1_LoadAwareSchedulingArgs(in *config.LoadAwareSchedulingArgs, out *LoadAwareSchedulingArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_NodeNUMAResourceArgs_To_config_NodeNUMAResourceArgs(in *NodeNUMAResourceArgs, out *config.NodeNUMAResourceArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	// WARNING: in.DefaultCPUBindPolicy requires manual conversion: inconvertible types (*github.com/koordinator-sh/koordinator/pkg/scheduler/apis/config/v1.CPUBindPolicy vs string)
	return nil
}

func autoConvert_config_NodeNUMAResourceArgs_To_v1_NodeNUMAResourceArgs(in *config.NodeNUMAResourceArgs, out *NodeNUMAResourceArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	// WARNING: in.DefaultCPUBindPolicy requires manual conversion: inconvertible types (string vs *github.com/koordinator-sh/koordinator/pkg/scheduler/apis/config/v1.CPUBindPolicy)
	return nil
}

func autoConvert_v1_NodeResourcesFitPlusArgs_To_config_NodeResourcesFitPlusArgs(in *NodeResourcesFitPlusArgs, out *config.NodeResourcesFitPlusArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_NodeResourcesFitPlusArgs_To_config_NodeResourcesFitPlusArgs is an autogenerated conversion function.
func Convert_v1_NodeResourcesFitPlusArgs_To_config_NodeResourcesFitPlusArgs(in *NodeResourcesFitPlusArgs, out *config.NodeResourcesFitPlusArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_NodeResourcesFitPlusArgs_To_v1_NodeResourcesFitPlusArgs(in *config.NodeResourcesFitPlusArgs, out *NodeResourcesFitPlusArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_NodeResourcesFitPlusArgs_To_v1_NodeResourcesFitPlusArgs is an autogenerated conversion function.
func Convert_config_NodeResourcesFitPlusArgs_To_v1_NodeResourcesFitPlusArgs(in *config.NodeResourcesFitPlusArgs, out *NodeResourcesFitPlusArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_PreAllocationConfig_To_config_PreAllocationConfig(in *PreAllocationConfig, out *config.PreAllocationConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_PreAllocationConfig_To_config_PreAllocationConfig is an autogenerated conversion function.
func Convert_v1_PreAllocationConfig_To_config_PreAllocationConfig(in *PreAllocationConfig, out *config.PreAllocationConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_PreAllocationConfig_To_v1_PreAllocationConfig(in *config.PreAllocationConfig, out *PreAllocationConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_PreAllocationConfig_To_v1_PreAllocationConfig is an autogenerated conversion function.
func Convert_config_PreAllocationConfig_To_v1_PreAllocationConfig(in *config.PreAllocationConfig, out *PreAllocationConfig, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_ReservationArgs_To_config_ReservationArgs(in *ReservationArgs, out *config.ReservationArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_ReservationArgs_To_config_ReservationArgs is an autogenerated conversion function.
func Convert_v1_ReservationArgs_To_config_ReservationArgs(in *ReservationArgs, out *config.ReservationArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_ReservationArgs_To_v1_ReservationArgs(in *config.ReservationArgs, out *ReservationArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_ReservationArgs_To_v1_ReservationArgs is an autogenerated conversion function.
func Convert_config_ReservationArgs_To_v1_ReservationArgs(in *config.ReservationArgs, out *ReservationArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_ResourcesType_To_config_ResourcesType(in *ResourcesType, out *config.ResourcesType, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_ResourcesType_To_config_ResourcesType is an autogenerated conversion function.
func Convert_v1_ResourcesType_To_config_ResourcesType(in *ResourcesType, out *config.ResourcesType, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_ResourcesType_To_v1_ResourcesType(in *config.ResourcesType, out *ResourcesType, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_ResourcesType_To_v1_ResourcesType is an autogenerated conversion function.
func Convert_config_ResourcesType_To_v1_ResourcesType(in *config.ResourcesType, out *ResourcesType, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_ScarceResourceAvoidanceArgs_To_config_ScarceResourceAvoidanceArgs(in *ScarceResourceAvoidanceArgs, out *config.ScarceResourceAvoidanceArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_ScarceResourceAvoidanceArgs_To_config_ScarceResourceAvoidanceArgs is an autogenerated conversion function.
func Convert_v1_ScarceResourceAvoidanceArgs_To_config_ScarceResourceAvoidanceArgs(in *ScarceResourceAvoidanceArgs, out *config.ScarceResourceAvoidanceArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_ScarceResourceAvoidanceArgs_To_v1_ScarceResourceAvoidanceArgs(in *config.ScarceResourceAvoidanceArgs, out *ScarceResourceAvoidanceArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_ScarceResourceAvoidanceArgs_To_v1_ScarceResourceAvoidanceArgs is an autogenerated conversion function.
func Convert_config_ScarceResourceAvoidanceArgs_To_v1_ScarceResourceAvoidanceArgs(in *config.ScarceResourceAvoidanceArgs, out *ScarceResourceAvoidanceArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_SchedulingHintArgs_To_config_SchedulingHintArgs(in *SchedulingHintArgs, out *config.SchedulingHintArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_SchedulingHintArgs_To_config_SchedulingHintArgs is an autogenerated conversion function.
func Convert_v1_SchedulingHintArgs_To_config_SchedulingHintArgs(in *SchedulingHintArgs, out *config.SchedulingHintArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_SchedulingHintArgs_To_v1_SchedulingHintArgs(in *config.SchedulingHintArgs, out *SchedulingHintArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_SchedulingHintArgs_To_v1_SchedulingHintArgs is an autogenerated conversion function.
func Convert_config_SchedulingHintArgs_To_v1_SchedulingHintArgs(in *config.SchedulingHintArgs, out *SchedulingHintArgs, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1_ScoringStrategy_To_config_ScoringStrategy(in *ScoringStrategy, out *config.ScoringStrategy, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1_ScoringStrategy_To_config_ScoringStrategy is an autogenerated conversion function.
func Convert_v1_ScoringStrategy_To_config_ScoringStrategy(in *ScoringStrategy, out *config.ScoringStrategy, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_config_ScoringStrategy_To_v1_ScoringStrategy(in *config.ScoringStrategy, out *ScoringStrategy, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_config_ScoringStrategy_To_v1_ScoringStrategy is an autogenerated conversion function.
func Convert_config_ScoringStrategy_To_v1_ScoringStrategy(in *config.ScoringStrategy, out *ScoringStrategy, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}
