// /*
// Copyright 2022 The Koordinator Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api_grpc.pb.go -destination pkg/koordlet/util/runtime/handler/mockclient/mock.go -copyright_file ./hack/boilerplate/boilerplate.go.txt -package mock_client RuntimeServiceClient
//

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	v1 "k8s.io/cri-api/pkg/apis/runtime/v1"
)

// MockRuntimeServiceClient is a mock of RuntimeServiceClient interface.
type MockRuntimeServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeServiceClientMockRecorder
	isgomock struct{}
}

// MockRuntimeServiceClientMockRecorder is the mock recorder for MockRuntimeServiceClient.
type MockRuntimeServiceClientMockRecorder struct {
	mock *MockRuntimeServiceClient
}

// NewMockRuntimeServiceClient creates a new mock instance.
func NewMockRuntimeServiceClient(ctrl *gomock.Controller) *MockRuntimeServiceClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeServiceClient) EXPECT() *MockRuntimeServiceClientMockRecorder {
	_ = "STUB: not implemented"

	// Attach mocks base method.
	return nil
}

func (m *MockRuntimeServiceClient) Attach(ctx context.Context, in *v1.AttachRequest, opts ...grpc.CallOption) (*v1.AttachResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Attach indicates an expected call of Attach.
func (mr *MockRuntimeServiceClientMockRecorder) Attach(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CheckpointContainer mocks base method.
func (m *MockRuntimeServiceClient) CheckpointContainer(ctx context.Context, in *v1.CheckpointContainerRequest, opts ...grpc.CallOption) (*v1.CheckpointContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CheckpointContainer indicates an expected call of CheckpointContainer.
func (mr *MockRuntimeServiceClientMockRecorder) CheckpointContainer(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStats mocks base method.
func (m *MockRuntimeServiceClient) ContainerStats(ctx context.Context, in *v1.ContainerStatsRequest, opts ...grpc.CallOption) (*v1.ContainerStatsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ContainerStats indicates an expected call of ContainerStats.
func (mr *MockRuntimeServiceClientMockRecorder) ContainerStats(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStatus mocks base method.
func (m *MockRuntimeServiceClient) ContainerStatus(ctx context.Context, in *v1.ContainerStatusRequest, opts ...grpc.CallOption) (*v1.ContainerStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ContainerStatus indicates an expected call of ContainerStatus.
func (mr *MockRuntimeServiceClientMockRecorder) ContainerStatus(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateContainer mocks base method.
func (m *MockRuntimeServiceClient) CreateContainer(ctx context.Context, in *v1.CreateContainerRequest, opts ...grpc.CallOption) (*v1.CreateContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockRuntimeServiceClientMockRecorder) CreateContainer(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Exec mocks base method.
func (m *MockRuntimeServiceClient) Exec(ctx context.Context, in *v1.ExecRequest, opts ...grpc.CallOption) (*v1.ExecResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Exec indicates an expected call of Exec.
func (mr *MockRuntimeServiceClientMockRecorder) Exec(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecSync mocks base method.
func (m *MockRuntimeServiceClient) ExecSync(ctx context.Context, in *v1.ExecSyncRequest, opts ...grpc.CallOption) (*v1.ExecSyncResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ExecSync indicates an expected call of ExecSync.
func (mr *MockRuntimeServiceClientMockRecorder) ExecSync(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetContainerEvents mocks base method.
func (m *MockRuntimeServiceClient) GetContainerEvents(ctx context.Context, in *v1.GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.ContainerEventResponse], error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetContainerEvents indicates an expected call of GetContainerEvents.
func (mr *MockRuntimeServiceClientMockRecorder) GetContainerEvents(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListContainerStats mocks base method.
func (m *MockRuntimeServiceClient) ListContainerStats(ctx context.Context, in *v1.ListContainerStatsRequest, opts ...grpc.CallOption) (*v1.ListContainerStatsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListContainerStats indicates an expected call of ListContainerStats.
func (mr *MockRuntimeServiceClientMockRecorder) ListContainerStats(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListContainers mocks base method.
func (m *MockRuntimeServiceClient) ListContainers(ctx context.Context, in *v1.ListContainersRequest, opts ...grpc.CallOption) (*v1.ListContainersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListContainers indicates an expected call of ListContainers.
func (mr *MockRuntimeServiceClientMockRecorder) ListContainers(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListMetricDescriptors mocks base method.
func (m *MockRuntimeServiceClient) ListMetricDescriptors(ctx context.Context, in *v1.ListMetricDescriptorsRequest, opts ...grpc.CallOption) (*v1.ListMetricDescriptorsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMetricDescriptors indicates an expected call of ListMetricDescriptors.
func (mr *MockRuntimeServiceClientMockRecorder) ListMetricDescriptors(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListPodSandbox mocks base method.
func (m *MockRuntimeServiceClient) ListPodSandbox(ctx context.Context, in *v1.ListPodSandboxRequest, opts ...grpc.CallOption) (*v1.ListPodSandboxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPodSandbox indicates an expected call of ListPodSandbox.
func (mr *MockRuntimeServiceClientMockRecorder) ListPodSandbox(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListPodSandboxMetrics mocks base method.
func (m *MockRuntimeServiceClient) ListPodSandboxMetrics(ctx context.Context, in *v1.ListPodSandboxMetricsRequest, opts ...grpc.CallOption) (*v1.ListPodSandboxMetricsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPodSandboxMetrics indicates an expected call of ListPodSandboxMetrics.
func (mr *MockRuntimeServiceClientMockRecorder) ListPodSandboxMetrics(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListPodSandboxStats mocks base method.
func (m *MockRuntimeServiceClient) ListPodSandboxStats(ctx context.Context, in *v1.ListPodSandboxStatsRequest, opts ...grpc.CallOption) (*v1.ListPodSandboxStatsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPodSandboxStats indicates an expected call of ListPodSandboxStats.
func (mr *MockRuntimeServiceClientMockRecorder) ListPodSandboxStats(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PodSandboxStats mocks base method.
func (m *MockRuntimeServiceClient) PodSandboxStats(ctx context.Context, in *v1.PodSandboxStatsRequest, opts ...grpc.CallOption) (*v1.PodSandboxStatsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PodSandboxStats indicates an expected call of PodSandboxStats.
func (mr *MockRuntimeServiceClientMockRecorder) PodSandboxStats(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PodSandboxStatus mocks base method.
func (m *MockRuntimeServiceClient) PodSandboxStatus(ctx context.Context, in *v1.PodSandboxStatusRequest, opts ...grpc.CallOption) (*v1.PodSandboxStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PodSandboxStatus indicates an expected call of PodSandboxStatus.
func (mr *MockRuntimeServiceClientMockRecorder) PodSandboxStatus(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PortForward mocks base method.
func (m *MockRuntimeServiceClient) PortForward(ctx context.Context, in *v1.PortForwardRequest, opts ...grpc.CallOption) (*v1.PortForwardResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PortForward indicates an expected call of PortForward.
func (mr *MockRuntimeServiceClientMockRecorder) PortForward(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveContainer mocks base method.
func (m *MockRuntimeServiceClient) RemoveContainer(ctx context.Context, in *v1.RemoveContainerRequest, opts ...grpc.CallOption) (*v1.RemoveContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveContainer indicates an expected call of RemoveContainer.
func (mr *MockRuntimeServiceClientMockRecorder) RemoveContainer(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemovePodSandbox mocks base method.
func (m *MockRuntimeServiceClient) RemovePodSandbox(ctx context.Context, in *v1.RemovePodSandboxRequest, opts ...grpc.CallOption) (*v1.RemovePodSandboxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemovePodSandbox indicates an expected call of RemovePodSandbox.
func (mr *MockRuntimeServiceClientMockRecorder) RemovePodSandbox(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReopenContainerLog mocks base method.
func (m *MockRuntimeServiceClient) ReopenContainerLog(ctx context.Context, in *v1.ReopenContainerLogRequest, opts ...grpc.CallOption) (*v1.ReopenContainerLogResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReopenContainerLog indicates an expected call of ReopenContainerLog.
func (mr *MockRuntimeServiceClientMockRecorder) ReopenContainerLog(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RunPodSandbox mocks base method.
func (m *MockRuntimeServiceClient) RunPodSandbox(ctx context.Context, in *v1.RunPodSandboxRequest, opts ...grpc.CallOption) (*v1.RunPodSandboxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RunPodSandbox indicates an expected call of RunPodSandbox.
func (mr *MockRuntimeServiceClientMockRecorder) RunPodSandbox(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RuntimeConfig mocks base method.
func (m *MockRuntimeServiceClient) RuntimeConfig(ctx context.Context, in *v1.RuntimeConfigRequest, opts ...grpc.CallOption) (*v1.RuntimeConfigResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RuntimeConfig indicates an expected call of RuntimeConfig.
func (mr *MockRuntimeServiceClientMockRecorder) RuntimeConfig(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StartContainer mocks base method.
func (m *MockRuntimeServiceClient) StartContainer(ctx context.Context, in *v1.StartContainerRequest, opts ...grpc.CallOption) (*v1.StartContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StartContainer indicates an expected call of StartContainer.
func (mr *MockRuntimeServiceClientMockRecorder) StartContainer(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Status mocks base method.
func (m *MockRuntimeServiceClient) Status(ctx context.Context, in *v1.StatusRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Status indicates an expected call of Status.
func (mr *MockRuntimeServiceClientMockRecorder) Status(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StopContainer mocks base method.
func (m *MockRuntimeServiceClient) StopContainer(ctx context.Context, in *v1.StopContainerRequest, opts ...grpc.CallOption) (*v1.StopContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StopContainer indicates an expected call of StopContainer.
func (mr *MockRuntimeServiceClientMockRecorder) StopContainer(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StopPodSandbox mocks base method.
func (m *MockRuntimeServiceClient) StopPodSandbox(ctx context.Context, in *v1.StopPodSandboxRequest, opts ...grpc.CallOption) (*v1.StopPodSandboxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StopPodSandbox indicates an expected call of StopPodSandbox.
func (mr *MockRuntimeServiceClientMockRecorder) StopPodSandbox(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateContainerResources mocks base method.
func (m *MockRuntimeServiceClient) UpdateContainerResources(ctx context.Context, in *v1.UpdateContainerResourcesRequest, opts ...grpc.CallOption) (*v1.UpdateContainerResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateContainerResources indicates an expected call of UpdateContainerResources.
func (mr *MockRuntimeServiceClientMockRecorder) UpdateContainerResources(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdatePodSandboxResources mocks base method.
func (m *MockRuntimeServiceClient) UpdatePodSandboxResources(ctx context.Context, in *v1.UpdatePodSandboxResourcesRequest, opts ...grpc.CallOption) (*v1.UpdatePodSandboxResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdatePodSandboxResources indicates an expected call of UpdatePodSandboxResources.
func (mr *MockRuntimeServiceClientMockRecorder) UpdatePodSandboxResources(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRuntimeConfig mocks base method.
func (m *MockRuntimeServiceClient) UpdateRuntimeConfig(ctx context.Context, in *v1.UpdateRuntimeConfigRequest, opts ...grpc.CallOption) (*v1.UpdateRuntimeConfigResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRuntimeConfig indicates an expected call of UpdateRuntimeConfig.
func (mr *MockRuntimeServiceClientMockRecorder) UpdateRuntimeConfig(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Version mocks base method.
func (m *MockRuntimeServiceClient) Version(ctx context.Context, in *v1.VersionRequest, opts ...grpc.CallOption) (*v1.VersionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Version indicates an expected call of Version.
func (mr *MockRuntimeServiceClientMockRecorder) Version(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRuntimeServiceServer is a mock of RuntimeServiceServer interface.
type MockRuntimeServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeServiceServerMockRecorder
	isgomock struct{}
}

// MockRuntimeServiceServerMockRecorder is the mock recorder for MockRuntimeServiceServer.
type MockRuntimeServiceServerMockRecorder struct {
	mock *MockRuntimeServiceServer
}

// NewMockRuntimeServiceServer creates a new mock instance.
func NewMockRuntimeServiceServer(ctrl *gomock.Controller) *MockRuntimeServiceServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeServiceServer) EXPECT() *MockRuntimeServiceServerMockRecorder {
	_ = "STUB: not implemented"

	// Attach mocks base method.
	return nil
}

func (m *MockRuntimeServiceServer) Attach(arg0 context.Context, arg1 *v1.AttachRequest) (*v1.AttachResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Attach indicates an expected call of Attach.
func (mr *MockRuntimeServiceServerMockRecorder) Attach(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CheckpointContainer mocks base method.
func (m *MockRuntimeServiceServer) CheckpointContainer(arg0 context.Context, arg1 *v1.CheckpointContainerRequest) (*v1.CheckpointContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CheckpointContainer indicates an expected call of CheckpointContainer.
func (mr *MockRuntimeServiceServerMockRecorder) CheckpointContainer(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStats mocks base method.
func (m *MockRuntimeServiceServer) ContainerStats(arg0 context.Context, arg1 *v1.ContainerStatsRequest) (*v1.ContainerStatsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ContainerStats indicates an expected call of ContainerStats.
func (mr *MockRuntimeServiceServerMockRecorder) ContainerStats(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStatus mocks base method.
func (m *MockRuntimeServiceServer) ContainerStatus(arg0 context.Context, arg1 *v1.ContainerStatusRequest) (*v1.ContainerStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ContainerStatus indicates an expected call of ContainerStatus.
func (mr *MockRuntimeServiceServerMockRecorder) ContainerStatus(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateContainer mocks base method.
func (m *MockRuntimeServiceServer) CreateContainer(arg0 context.Context, arg1 *v1.CreateContainerRequest) (*v1.CreateContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockRuntimeServiceServerMockRecorder) CreateContainer(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Exec mocks base method.
func (m *MockRuntimeServiceServer) Exec(arg0 context.Context, arg1 *v1.ExecRequest) (*v1.ExecResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Exec indicates an expected call of Exec.
func (mr *MockRuntimeServiceServerMockRecorder) Exec(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecSync mocks base method.
func (m *MockRuntimeServiceServer) ExecSync(arg0 context.Context, arg1 *v1.ExecSyncRequest) (*v1.ExecSyncResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ExecSync indicates an expected call of ExecSync.
func (mr *MockRuntimeServiceServerMockRecorder) ExecSync(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetContainerEvents mocks base method.
func (m *MockRuntimeServiceServer) GetContainerEvents(arg0 *v1.GetEventsRequest, arg1 grpc.ServerStreamingServer[v1.ContainerEventResponse]) error {
	_ = "STUB: not implemented"
	return nil
}

// GetContainerEvents indicates an expected call of GetContainerEvents.
func (mr *MockRuntimeServiceServerMockRecorder) GetContainerEvents(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListContainerStats mocks base method.
func (m *MockRuntimeServiceServer) ListContainerStats(arg0 context.Context, arg1 *v1.ListContainerStatsRequest) (*v1.ListContainerStatsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListContainerStats indicates an expected call of ListContainerStats.
func (mr *MockRuntimeServiceServerMockRecorder) ListContainerStats(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListContainers mocks base method.
func (m *MockRuntimeServiceServer) ListContainers(arg0 context.Context, arg1 *v1.ListContainersRequest) (*v1.ListContainersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListContainers indicates an expected call of ListContainers.
func (mr *MockRuntimeServiceServerMockRecorder) ListContainers(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListMetricDescriptors mocks base method.
func (m *MockRuntimeServiceServer) ListMetricDescriptors(arg0 context.Context, arg1 *v1.ListMetricDescriptorsRequest) (*v1.ListMetricDescriptorsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListMetricDescriptors indicates an expected call of ListMetricDescriptors.
func (mr *MockRuntimeServiceServerMockRecorder) ListMetricDescriptors(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListPodSandbox mocks base method.
func (m *MockRuntimeServiceServer) ListPodSandbox(arg0 context.Context, arg1 *v1.ListPodSandboxRequest) (*v1.ListPodSandboxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPodSandbox indicates an expected call of ListPodSandbox.
func (mr *MockRuntimeServiceServerMockRecorder) ListPodSandbox(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListPodSandboxMetrics mocks base method.
func (m *MockRuntimeServiceServer) ListPodSandboxMetrics(arg0 context.Context, arg1 *v1.ListPodSandboxMetricsRequest) (*v1.ListPodSandboxMetricsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPodSandboxMetrics indicates an expected call of ListPodSandboxMetrics.
func (mr *MockRuntimeServiceServerMockRecorder) ListPodSandboxMetrics(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListPodSandboxStats mocks base method.
func (m *MockRuntimeServiceServer) ListPodSandboxStats(arg0 context.Context, arg1 *v1.ListPodSandboxStatsRequest) (*v1.ListPodSandboxStatsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListPodSandboxStats indicates an expected call of ListPodSandboxStats.
func (mr *MockRuntimeServiceServerMockRecorder) ListPodSandboxStats(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PodSandboxStats mocks base method.
func (m *MockRuntimeServiceServer) PodSandboxStats(arg0 context.Context, arg1 *v1.PodSandboxStatsRequest) (*v1.PodSandboxStatsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PodSandboxStats indicates an expected call of PodSandboxStats.
func (mr *MockRuntimeServiceServerMockRecorder) PodSandboxStats(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PodSandboxStatus mocks base method.
func (m *MockRuntimeServiceServer) PodSandboxStatus(arg0 context.Context, arg1 *v1.PodSandboxStatusRequest) (*v1.PodSandboxStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PodSandboxStatus indicates an expected call of PodSandboxStatus.
func (mr *MockRuntimeServiceServerMockRecorder) PodSandboxStatus(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PortForward mocks base method.
func (m *MockRuntimeServiceServer) PortForward(arg0 context.Context, arg1 *v1.PortForwardRequest) (*v1.PortForwardResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PortForward indicates an expected call of PortForward.
func (mr *MockRuntimeServiceServerMockRecorder) PortForward(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveContainer mocks base method.
func (m *MockRuntimeServiceServer) RemoveContainer(arg0 context.Context, arg1 *v1.RemoveContainerRequest) (*v1.RemoveContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveContainer indicates an expected call of RemoveContainer.
func (mr *MockRuntimeServiceServerMockRecorder) RemoveContainer(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemovePodSandbox mocks base method.
func (m *MockRuntimeServiceServer) RemovePodSandbox(arg0 context.Context, arg1 *v1.RemovePodSandboxRequest) (*v1.RemovePodSandboxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemovePodSandbox indicates an expected call of RemovePodSandbox.
func (mr *MockRuntimeServiceServerMockRecorder) RemovePodSandbox(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReopenContainerLog mocks base method.
func (m *MockRuntimeServiceServer) ReopenContainerLog(arg0 context.Context, arg1 *v1.ReopenContainerLogRequest) (*v1.ReopenContainerLogResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReopenContainerLog indicates an expected call of ReopenContainerLog.
func (mr *MockRuntimeServiceServerMockRecorder) ReopenContainerLog(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RunPodSandbox mocks base method.
func (m *MockRuntimeServiceServer) RunPodSandbox(arg0 context.Context, arg1 *v1.RunPodSandboxRequest) (*v1.RunPodSandboxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RunPodSandbox indicates an expected call of RunPodSandbox.
func (mr *MockRuntimeServiceServerMockRecorder) RunPodSandbox(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RuntimeConfig mocks base method.
func (m *MockRuntimeServiceServer) RuntimeConfig(arg0 context.Context, arg1 *v1.RuntimeConfigRequest) (*v1.RuntimeConfigResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RuntimeConfig indicates an expected call of RuntimeConfig.
func (mr *MockRuntimeServiceServerMockRecorder) RuntimeConfig(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StartContainer mocks base method.
func (m *MockRuntimeServiceServer) StartContainer(arg0 context.Context, arg1 *v1.StartContainerRequest) (*v1.StartContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StartContainer indicates an expected call of StartContainer.
func (mr *MockRuntimeServiceServerMockRecorder) StartContainer(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Status mocks base method.
func (m *MockRuntimeServiceServer) Status(arg0 context.Context, arg1 *v1.StatusRequest) (*v1.StatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Status indicates an expected call of Status.
func (mr *MockRuntimeServiceServerMockRecorder) Status(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StopContainer mocks base method.
func (m *MockRuntimeServiceServer) StopContainer(arg0 context.Context, arg1 *v1.StopContainerRequest) (*v1.StopContainerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StopContainer indicates an expected call of StopContainer.
func (mr *MockRuntimeServiceServerMockRecorder) StopContainer(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StopPodSandbox mocks base method.
func (m *MockRuntimeServiceServer) StopPodSandbox(arg0 context.Context, arg1 *v1.StopPodSandboxRequest) (*v1.StopPodSandboxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StopPodSandbox indicates an expected call of StopPodSandbox.
func (mr *MockRuntimeServiceServerMockRecorder) StopPodSandbox(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateContainerResources mocks base method.
func (m *MockRuntimeServiceServer) UpdateContainerResources(arg0 context.Context, arg1 *v1.UpdateContainerResourcesRequest) (*v1.UpdateContainerResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateContainerResources indicates an expected call of UpdateContainerResources.
func (mr *MockRuntimeServiceServerMockRecorder) UpdateContainerResources(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdatePodSandboxResources mocks base method.
func (m *MockRuntimeServiceServer) UpdatePodSandboxResources(arg0 context.Context, arg1 *v1.UpdatePodSandboxResourcesRequest) (*v1.UpdatePodSandboxResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdatePodSandboxResources indicates an expected call of UpdatePodSandboxResources.
func (mr *MockRuntimeServiceServerMockRecorder) UpdatePodSandboxResources(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRuntimeConfig mocks base method.
func (m *MockRuntimeServiceServer) UpdateRuntimeConfig(arg0 context.Context, arg1 *v1.UpdateRuntimeConfigRequest) (*v1.UpdateRuntimeConfigResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateRuntimeConfig indicates an expected call of UpdateRuntimeConfig.
func (mr *MockRuntimeServiceServerMockRecorder) UpdateRuntimeConfig(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Version mocks base method.
func (m *MockRuntimeServiceServer) Version(arg0 context.Context, arg1 *v1.VersionRequest) (*v1.VersionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Version indicates an expected call of Version.
func (mr *MockRuntimeServiceServerMockRecorder) Version(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// mustEmbedUnimplementedRuntimeServiceServer mocks base method.
func (m *MockRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {
	_ = "STUB: not implemented"
	return
}

// mustEmbedUnimplementedRuntimeServiceServer indicates an expected call of mustEmbedUnimplementedRuntimeServiceServer.
func (mr *MockRuntimeServiceServerMockRecorder) mustEmbedUnimplementedRuntimeServiceServer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockUnsafeRuntimeServiceServer is a mock of UnsafeRuntimeServiceServer interface.
type MockUnsafeRuntimeServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeRuntimeServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeRuntimeServiceServerMockRecorder is the mock recorder for MockUnsafeRuntimeServiceServer.
type MockUnsafeRuntimeServiceServerMockRecorder struct {
	mock *MockUnsafeRuntimeServiceServer
}

// NewMockUnsafeRuntimeServiceServer creates a new mock instance.
func NewMockUnsafeRuntimeServiceServer(ctrl *gomock.Controller) *MockUnsafeRuntimeServiceServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeRuntimeServiceServer) EXPECT() *MockUnsafeRuntimeServiceServerMockRecorder {
	_ = "STUB: not implemented"

	// mustEmbedUnimplementedRuntimeServiceServer mocks base method.
	return nil
}

func (m *MockUnsafeRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {
	_ = "STUB: not implemented"
	return
}

// mustEmbedUnimplementedRuntimeServiceServer indicates an expected call of mustEmbedUnimplementedRuntimeServiceServer.
func (mr *MockUnsafeRuntimeServiceServerMockRecorder) mustEmbedUnimplementedRuntimeServiceServer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockImageServiceClient is a mock of ImageServiceClient interface.
type MockImageServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockImageServiceClientMockRecorder
	isgomock struct{}
}

// MockImageServiceClientMockRecorder is the mock recorder for MockImageServiceClient.
type MockImageServiceClientMockRecorder struct {
	mock *MockImageServiceClient
}

// NewMockImageServiceClient creates a new mock instance.
func NewMockImageServiceClient(ctrl *gomock.Controller) *MockImageServiceClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageServiceClient) EXPECT() *MockImageServiceClientMockRecorder {
	_ = "STUB: not implemented"

	// ImageFsInfo mocks base method.
	return nil
}

func (m *MockImageServiceClient) ImageFsInfo(ctx context.Context, in *v1.ImageFsInfoRequest, opts ...grpc.CallOption) (*v1.ImageFsInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImageFsInfo indicates an expected call of ImageFsInfo.
func (mr *MockImageServiceClientMockRecorder) ImageFsInfo(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ImageStatus mocks base method.
func (m *MockImageServiceClient) ImageStatus(ctx context.Context, in *v1.ImageStatusRequest, opts ...grpc.CallOption) (*v1.ImageStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImageStatus indicates an expected call of ImageStatus.
func (mr *MockImageServiceClientMockRecorder) ImageStatus(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListImages mocks base method.
func (m *MockImageServiceClient) ListImages(ctx context.Context, in *v1.ListImagesRequest, opts ...grpc.CallOption) (*v1.ListImagesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListImages indicates an expected call of ListImages.
func (mr *MockImageServiceClientMockRecorder) ListImages(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PullImage mocks base method.
func (m *MockImageServiceClient) PullImage(ctx context.Context, in *v1.PullImageRequest, opts ...grpc.CallOption) (*v1.PullImageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PullImage indicates an expected call of PullImage.
func (mr *MockImageServiceClientMockRecorder) PullImage(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveImage mocks base method.
func (m *MockImageServiceClient) RemoveImage(ctx context.Context, in *v1.RemoveImageRequest, opts ...grpc.CallOption) (*v1.RemoveImageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveImage indicates an expected call of RemoveImage.
func (mr *MockImageServiceClientMockRecorder) RemoveImage(ctx, in any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockImageServiceServer is a mock of ImageServiceServer interface.
type MockImageServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockImageServiceServerMockRecorder
	isgomock struct{}
}

// MockImageServiceServerMockRecorder is the mock recorder for MockImageServiceServer.
type MockImageServiceServerMockRecorder struct {
	mock *MockImageServiceServer
}

// NewMockImageServiceServer creates a new mock instance.
func NewMockImageServiceServer(ctrl *gomock.Controller) *MockImageServiceServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageServiceServer) EXPECT() *MockImageServiceServerMockRecorder {
	_ = "STUB: not implemented"

	// ImageFsInfo mocks base method.
	return nil
}

func (m *MockImageServiceServer) ImageFsInfo(arg0 context.Context, arg1 *v1.ImageFsInfoRequest) (*v1.ImageFsInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImageFsInfo indicates an expected call of ImageFsInfo.
func (mr *MockImageServiceServerMockRecorder) ImageFsInfo(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ImageStatus mocks base method.
func (m *MockImageServiceServer) ImageStatus(arg0 context.Context, arg1 *v1.ImageStatusRequest) (*v1.ImageStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ImageStatus indicates an expected call of ImageStatus.
func (mr *MockImageServiceServerMockRecorder) ImageStatus(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListImages mocks base method.
func (m *MockImageServiceServer) ListImages(arg0 context.Context, arg1 *v1.ListImagesRequest) (*v1.ListImagesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListImages indicates an expected call of ListImages.
func (mr *MockImageServiceServerMockRecorder) ListImages(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PullImage mocks base method.
func (m *MockImageServiceServer) PullImage(arg0 context.Context, arg1 *v1.PullImageRequest) (*v1.PullImageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PullImage indicates an expected call of PullImage.
func (mr *MockImageServiceServerMockRecorder) PullImage(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveImage mocks base method.
func (m *MockImageServiceServer) RemoveImage(arg0 context.Context, arg1 *v1.RemoveImageRequest) (*v1.RemoveImageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveImage indicates an expected call of RemoveImage.
func (mr *MockImageServiceServerMockRecorder) RemoveImage(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// mustEmbedUnimplementedImageServiceServer mocks base method.
func (m *MockImageServiceServer) mustEmbedUnimplementedImageServiceServer() {
	_ = "STUB: not implemented"
	return
}

// mustEmbedUnimplementedImageServiceServer indicates an expected call of mustEmbedUnimplementedImageServiceServer.
func (mr *MockImageServiceServerMockRecorder) mustEmbedUnimplementedImageServiceServer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockUnsafeImageServiceServer is a mock of UnsafeImageServiceServer interface.
type MockUnsafeImageServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeImageServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeImageServiceServerMockRecorder is the mock recorder for MockUnsafeImageServiceServer.
type MockUnsafeImageServiceServerMockRecorder struct {
	mock *MockUnsafeImageServiceServer
}

// NewMockUnsafeImageServiceServer creates a new mock instance.
func NewMockUnsafeImageServiceServer(ctrl *gomock.Controller) *MockUnsafeImageServiceServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeImageServiceServer) EXPECT() *MockUnsafeImageServiceServerMockRecorder {
	_ = "STUB: not implemented"

	// mustEmbedUnimplementedImageServiceServer mocks base method.
	return nil
}

func (m *MockUnsafeImageServiceServer) mustEmbedUnimplementedImageServiceServer() {
	_ = "STUB: not implemented"
	return
}

// mustEmbedUnimplementedImageServiceServer indicates an expected call of mustEmbedUnimplementedImageServiceServer.
func (mr *MockUnsafeImageServiceServerMockRecorder) mustEmbedUnimplementedImageServiceServer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
