/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/koordinator-sh/koordinator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterNetworkTopologies returns a ClusterNetworkTopologyInformer.
	ClusterNetworkTopologies() ClusterNetworkTopologyInformer
	// Devices returns a DeviceInformer.
	Devices() DeviceInformer
	// PodMigrationJobs returns a PodMigrationJobInformer.
	PodMigrationJobs() PodMigrationJobInformer
	// Reservations returns a ReservationInformer.
	Reservations() ReservationInformer
	// ScheduleExplanations returns a ScheduleExplanationInformer.
	ScheduleExplanations() ScheduleExplanationInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	_ = "STUB: not implemented"
	return *new(Interface)
}

// ClusterNetworkTopologies returns a ClusterNetworkTopologyInformer.
func (v *version) ClusterNetworkTopologies() ClusterNetworkTopologyInformer {
	_ = "STUB: not implemented"
	return *new(ClusterNetworkTopologyInformer)
}

// Devices returns a DeviceInformer.
func (v *version) Devices() DeviceInformer { _ = "STUB: not implemented"; return *new(DeviceInformer) }

// PodMigrationJobs returns a PodMigrationJobInformer.
func (v *version) PodMigrationJobs() PodMigrationJobInformer {
	_ = "STUB: not implemented"
	return *new(PodMigrationJobInformer)
}

// Reservations returns a ReservationInformer.
func (v *version) Reservations() ReservationInformer {
	_ = "STUB: not implemented"
	return *new(ReservationInformer)
}

// ScheduleExplanations returns a ScheduleExplanationInformer.
func (v *version) ScheduleExplanations() ScheduleExplanationInformer {
	_ = "STUB: not implemented"
	return *new(ScheduleExplanationInformer)
}
